package com.stu.cx.star.Entity;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.id
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.mobile
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.login_time
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    private String loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.login_ip
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    private String loginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.id
     *
     * @return the value of login_log.id
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.id
     *
     * @param id the value for login_log.id
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.mobile
     *
     * @return the value of login_log.mobile
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.mobile
     *
     * @param mobile the value for login_log.mobile
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.login_time
     *
     * @return the value of login_log.login_time
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.login_time
     *
     * @param loginTime the value for login_log.login_time
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.login_ip
     *
     * @return the value of login_log.login_ip
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.login_ip
     *
     * @param loginIp the value for login_log.login_ip
     *
     * @mbg.generated Wed Sep 25 10:25:38 CST 2019
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }
}