package com.stu.cx.star.Entity;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.name
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.salt
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.address
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.mobile
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.mail
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    private String mail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.name
     *
     * @return the value of login.name
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.name
     *
     * @param name the value for login.name
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.salt
     *
     * @return the value of login.salt
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.salt
     *
     * @param salt the value for login.salt
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.address
     *
     * @return the value of login.address
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.address
     *
     * @param address the value for login.address
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.mobile
     *
     * @return the value of login.mobile
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.mobile
     *
     * @param mobile the value for login.mobile
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.mail
     *
     * @return the value of login.mail
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.mail
     *
     * @param mail the value for login.mail
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }
}