package com.stu.cx.star.Dao;

import com.stu.cx.star.Entity.Login;
import com.stu.cx.star.Entity.LoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;


public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    long countByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int deleteByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    List<Login> selectByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    Login selectByPrimaryKey(Integer id);

    Login selectByMobile(String mobile);

    Login selectByMail(String mail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Login record, @Param("example") LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int updateByExample(@Param("record") Login record, @Param("example") LoginExample example);

    void updateByMail(@Param("mail")String mail,@Param("password")String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Wed Sep 18 15:00:16 CST 2019
     */
    int updateByPrimaryKey(Login record);
}